### ISSUE TITLE
Update to tokio 0.3?

### ISSUE THREAD

**Issue by vi** [nanpuyue/tokio-fd#1]
There is Tokio 0.3. Shall this crate toe the line?

**Comment by vi** [comment]
Or maybe README and crate-level doc should point to https://docs.rs/tokio/0.3.3/tokio/io/unix/struct.AsyncFd.html ?

No, it only does half of the job. No `AsyncRead`/`AsyncWrite`.

**Comment by nanpuyue** [comment]
@vi https://github.com/nanpuyue/tokio-fd/commit/4b263b8bcd6097e7157d66af6d6b3c1b20d29c5d

**Comment by vi** [comment]
Thanks.

When to expect 0.2.0 on crates.io?

**Comment by nanpuyue** [comment]
Published.

**Comment by vi** [comment]
Verified that it works.

Note that functions that allow operating with raw file descriptor are typically `unsafe`.

tokio::io::unix::AsyncFd is [not unsafe](https://github.com/tokio-rs/tokio/discussions/3147), but that's may be because of it's just adding things to epoll is not expected to break things. This library allows reading and writing from/to specific file descriptor, so may be more disruptive.
